### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by lief-erickson** [jekyll-one/j1-template-starter#1]
I'm looking to use this project and have a number of questions. Where is the best place to ask usage and clarification questions? 

For example, from `_data/layouts/page.yml` ([Lines 146-149](https://github.com/jekyll-one/j1-template-starter/blob/main/_data/layouts/page.yml#L146-L149)):

> The CONTENT of a PAGE is passed trough a (Liquid) wrapper procedure (page_content.html) to add or inject specific ADDITIONAL data like a TOC etc. that influences the resulting page.

`page_content.html` does not exist in the project. What is the correct file name?

Do you accept pull requests?

**Comment by jekyll-one** [comment]
The best place is (here) at jekyll-one/jekyll-one. I'll remove the issues
section at the repo jekyll-one/j1-template-starter.

The repo @jekyll-one/j1-template-starter is used ONLY for technical reasons. Some sites present my example webs but use HTML iFrames to display. To make using  HTML iFrames possible, some cookie settings are to be adjusted. These settings allow so-called 'cross-site' requests and are NOT recommended for public websites on the Internet. In other words: you need to know what you're doing if 'cross-site' requests are allowed for a site. The default cookie settings for J1-based webs reject 'cross-site' requests for security reasons.

The issues section (support) is mainly used to raise attention on errors or other misbehavior for code fixing. Usage questions (consulting) can only be answered very limitedly, or they are rejected. Questions addressing the usage of J1 as a tool are often too open or focussing on technical areas like the usage of Cookies, Webdesign or the generator Jekyll. It would be best if you asked questions for consulting on forum websites like http://stackoverflow.com/questions/tagged/jekyll or http://jekyll.tips/.


Do you accept pull requests?

Yes, sure. I'm open for any suggestion or for help on fixing issues.

**Comment by y377** [comment]
@jekyll-one hi 
This is the most handsome website developed by Jekyll that I have seen so far. It is more beautiful than the official website. I am also learning Jekyll development systematically. I am very glad to have browsed your website.
 > I didn't expect you to spend 4 years, I admire your courage
