### ISSUE TITLE
Problems in installing in WSL 2 Windows 10

### ISSUE THREAD

**Issue by gsilvestri** [jekyll-one/j1-template-starter#3]
Good afternoon,
I have the following error while installing the framework in Kali Linux in Windows Subsystem for Linux 2 in Windows 10
```
/home/kali/.gem/ruby/3.0.0/gems/asciidoctor-rouge-0.4.0/lib/asciidoctor/rouge/treeprocessor.rb:30:in `initialize': asciidoctor: FAILED: /home/kali/workspace/jekyll-one/pages/public/asciidoc_skeletons/documentation/000_intro.adoc: Failed to load AsciiDoc document - wrong number of arguments (given 1, expected 0) (ArgumentError)
        from /home/kali/.gem/ruby/3.0.0/gems/asciidoctor-1.5.8/lib/asciidoctor/extensions.rb:1349:in `new'
        from /home/kali/.gem/ruby/3.0.0/gems/asciidoctor-1.5.8/lib/asciidoctor/extensions.rb:1349:in `add_document_processor'
        from /home/kali/.gem/ruby/3.0.0/gems/asciidoctor-1.5.8/lib/asciidoctor/extensions.rb:822:in `tree_processor'
        from /home/kali/.gem/ruby/3.0.0/gems/asciidoctor-rouge-0.4.0/lib/asciidoctor/rouge.rb:9:in `block in <top (required)>'
/home/kali/.gem/ruby/3.0.0/gems/asciidoctor-rouge-0.4.0/lib/asciidoctor/rouge/treeprocessor.rb:30:in `initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)
        from /home/kali/.gem/ruby/3.0.0/gems/asciidoctor-1.5.8/lib/asciidoctor/extensions.rb:1349:in `new'
        from /home/kali/.gem/ruby/3.0.0/gems/asciidoctor-1.5.8/lib/asciidoctor/extensions.rb:1349:in `add_document_processor'
        from /home/kali/.gem/ruby/3.0.0/gems/asciidoctor-1.5.8/lib/asciidoctor/extensions.rb:822:in `tree_processor'
        from /home/kali/.gem/ruby/3.0.0/gems/asciidoctor-rouge-0.4.0/lib/asciidoctor/rouge.rb:9:in `block in <top (required)>'
```
How can I fix this problem?

**OS**: Windows 10
**WSL 2**: Kali GNU/Linux Rolling 2022.2
**Ruby**: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux-gnu]

**Comment by gsilvestri** [comment]
I have the same problem installing in Windows 10 without WSL 2.

**Comment by jekyll-one** [comment]
Hi,

thanks for giving J1 Template a try.

From the data you've given, **Ruby V3** is used  to run the project. The current version of J1 Template (2022.4.x) does **not** support Ruby V3 as described in the README, section **Development languages and tools**.

For J1 Template, a change to Ruby V3 is in progress for version **2022.5.x** but not available yet. The release date for the new version is planned for early August 2022. To use the **release candidate** version of 2022.5.x, go for [RubyGems](https://rubygems.org/gems/j1-template) 


Regard,
Juergen
